name: Scheduled Job

on:
  schedule:
    - cron: "0 * * * *"
    - cron: "*/15 8-10 * * *"

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - run: node ./appp.js
